// Code generated by counterfeiter. DO NOT EDIT.
package capturepageslogicfakes

import (
	"context"
	"sync"

	"github.com/dembygenesis/local.tools/internal/model"
	"github.com/dembygenesis/local.tools/internal/persistence"
)

type FakePersistor struct {
	GetCapturePagesStub        func(context.Context, persistence.TransactionHandler, *model.CapturePagesFilters) (*model.PaginatedCapturePages, error)
	getCapturePagesMutex       sync.RWMutex
	getCapturePagesArgsForCall []struct {
		arg1 context.Context
		arg2 persistence.TransactionHandler
		arg3 *model.CapturePagesFilters
	}
	getCapturePagesReturns struct {
		result1 *model.PaginatedCapturePages
		result2 error
	}
	getCapturePagesReturnsOnCall map[int]struct {
		result1 *model.PaginatedCapturePages
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePersistor) GetCapturePages(arg1 context.Context, arg2 persistence.TransactionHandler, arg3 *model.CapturePagesFilters) (*model.PaginatedCapturePages, error) {
	fake.getCapturePagesMutex.Lock()
	ret, specificReturn := fake.getCapturePagesReturnsOnCall[len(fake.getCapturePagesArgsForCall)]
	fake.getCapturePagesArgsForCall = append(fake.getCapturePagesArgsForCall, struct {
		arg1 context.Context
		arg2 persistence.TransactionHandler
		arg3 *model.CapturePagesFilters
	}{arg1, arg2, arg3})
	stub := fake.GetCapturePagesStub
	fakeReturns := fake.getCapturePagesReturns
	fake.recordInvocation("GetCapturePages", []interface{}{arg1, arg2, arg3})
	fake.getCapturePagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePersistor) GetCapturePagesCallCount() int {
	fake.getCapturePagesMutex.RLock()
	defer fake.getCapturePagesMutex.RUnlock()
	return len(fake.getCapturePagesArgsForCall)
}

func (fake *FakePersistor) GetCapturePagesCalls(stub func(context.Context, persistence.TransactionHandler, *model.CapturePagesFilters) (*model.PaginatedCapturePages, error)) {
	fake.getCapturePagesMutex.Lock()
	defer fake.getCapturePagesMutex.Unlock()
	fake.GetCapturePagesStub = stub
}

func (fake *FakePersistor) GetCapturePagesArgsForCall(i int) (context.Context, persistence.TransactionHandler, *model.CapturePagesFilters) {
	fake.getCapturePagesMutex.RLock()
	defer fake.getCapturePagesMutex.RUnlock()
	argsForCall := fake.getCapturePagesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePersistor) GetCapturePagesReturns(result1 *model.PaginatedCapturePages, result2 error) {
	fake.getCapturePagesMutex.Lock()
	defer fake.getCapturePagesMutex.Unlock()
	fake.GetCapturePagesStub = nil
	fake.getCapturePagesReturns = struct {
		result1 *model.PaginatedCapturePages
		result2 error
	}{result1, result2}
}

func (fake *FakePersistor) GetCapturePagesReturnsOnCall(i int, result1 *model.PaginatedCapturePages, result2 error) {
	fake.getCapturePagesMutex.Lock()
	defer fake.getCapturePagesMutex.Unlock()
	fake.GetCapturePagesStub = nil
	if fake.getCapturePagesReturnsOnCall == nil {
		fake.getCapturePagesReturnsOnCall = make(map[int]struct {
			result1 *model.PaginatedCapturePages
			result2 error
		})
	}
	fake.getCapturePagesReturnsOnCall[i] = struct {
		result1 *model.PaginatedCapturePages
		result2 error
	}{result1, result2}
}

func (fake *FakePersistor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getCapturePagesMutex.RLock()
	defer fake.getCapturePagesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePersistor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
