version: "3.7"

services:
  controller:
    command: sh /entrypoint.sh
    build:
      dockerfile: api.dockerfile
      context: ./docker
      args:
        ENTRYPOINT: "entrypoint.sh"
    networks:
      - default
    env_file:
      - api.env
    working_dir: /
    volumes:
      - ../:/src

networks:
  default:

volumes:
  controller: