version: "3.7"

services:
  db:
    env_file:
      - db.env
    container_name: "mysql_container"
    networks:
      - default
    restart: always
    image: mysql:8.0
    ports:
      # - 3341:3341
      - "3337:3306"
      - "3337:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_TCP_PORT: "3341"
      MYSQL_DATABASE: "theoverwatchtools"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""

  # Fuck
  controller:
    # command: /bin/bash -c "CompileDaemon -build='go build -o=/tmp/uplb/controller ./cmd/controller' -command='/tmp/uplb/controller controller' -graceful-kill=true"
    # command: sh /entrypoint.sh
    # command: /bin/bash -c "CompileDaemon -build='go build -o=/tmp/uplb/controller ./cmd/controller' -command='/tmp/uplb/controller controller' -graceful-kill=true"
    # command: wait-for ${MYSQL_ROOT_PASSWORD} && /bin/bash -c "CompileDaemon -build='go build -o=/tmp/uplb/controller ./cmd/controller' -command='/tmp/uplb/controller controller' -graceful-kill=true"
    command: /bin/bash -c "wait-for db:${MYSQL_TCP_PORT} && CompileDaemon -build='go build -o=/tmp/uplb/controller ./cmd/controller' -command='/tmp/uplb/controller controller' -graceful-kill=true"
    # command: /bin/bash -c "CompileDaemon -build='go build -o=/tmp/uplb/controller ./cmd/controller' -command='/tmp/uplb/controller controller' -graceful-kill=true"
    build:
      dockerfile: api.dockerfile
      context: ./docker
      args:
        ENTRYPOINT: "entrypoint.sh"
    networks:
      - default
    env_file:
      - api.env
    working_dir: /
    volumes:
      - ../:/src

networks:
  default:

volumes:
  controller: