// Code generated by counterfeiter. DO NOT EDIT.
package strsrvutilfakes

import (
	"sync"
)

type FakeOsLayer struct {
	CopyRootPathToClipboardStub        func(string, []string) ([]string, error)
	copyRootPathToClipboardMutex       sync.RWMutex
	copyRootPathToClipboardArgsForCall []struct {
		arg1 string
		arg2 []string
	}
	copyRootPathToClipboardReturns struct {
		result1 []string
		result2 error
	}
	copyRootPathToClipboardReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeOsLayer) CopyRootPathToClipboard(arg1 string, arg2 []string) ([]string, error) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.copyRootPathToClipboardMutex.Lock()
	ret, specificReturn := fake.copyRootPathToClipboardReturnsOnCall[len(fake.copyRootPathToClipboardArgsForCall)]
	fake.copyRootPathToClipboardArgsForCall = append(fake.copyRootPathToClipboardArgsForCall, struct {
		arg1 string
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.CopyRootPathToClipboardStub
	fakeReturns := fake.copyRootPathToClipboardReturns
	fake.recordInvocation("CopyRootPathToClipboard", []interface{}{arg1, arg2Copy})
	fake.copyRootPathToClipboardMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOsLayer) CopyRootPathToClipboardCallCount() int {
	fake.copyRootPathToClipboardMutex.RLock()
	defer fake.copyRootPathToClipboardMutex.RUnlock()
	return len(fake.copyRootPathToClipboardArgsForCall)
}

func (fake *FakeOsLayer) CopyRootPathToClipboardCalls(stub func(string, []string) ([]string, error)) {
	fake.copyRootPathToClipboardMutex.Lock()
	defer fake.copyRootPathToClipboardMutex.Unlock()
	fake.CopyRootPathToClipboardStub = stub
}

func (fake *FakeOsLayer) CopyRootPathToClipboardArgsForCall(i int) (string, []string) {
	fake.copyRootPathToClipboardMutex.RLock()
	defer fake.copyRootPathToClipboardMutex.RUnlock()
	argsForCall := fake.copyRootPathToClipboardArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOsLayer) CopyRootPathToClipboardReturns(result1 []string, result2 error) {
	fake.copyRootPathToClipboardMutex.Lock()
	defer fake.copyRootPathToClipboardMutex.Unlock()
	fake.CopyRootPathToClipboardStub = nil
	fake.copyRootPathToClipboardReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeOsLayer) CopyRootPathToClipboardReturnsOnCall(i int, result1 []string, result2 error) {
	fake.copyRootPathToClipboardMutex.Lock()
	defer fake.copyRootPathToClipboardMutex.Unlock()
	fake.CopyRootPathToClipboardStub = nil
	if fake.copyRootPathToClipboardReturnsOnCall == nil {
		fake.copyRootPathToClipboardReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.copyRootPathToClipboardReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeOsLayer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.copyRootPathToClipboardMutex.RLock()
	defer fake.copyRootPathToClipboardMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeOsLayer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
