// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mysqlmodel

var TableNames = struct {
	CapturePage      string
	CapturePageSet   string
	Category         string
	CategoryType     string
	ClickTracker     string
	ClickTrackerLog  string
	ClickTrackerSet  string
	Organization     string
	SchemaMigrations string
	User             string
}{
	CapturePage:      "capture_page",
	CapturePageSet:   "capture_page_set",
	Category:         "category",
	CategoryType:     "category_type",
	ClickTracker:     "click_tracker",
	ClickTrackerLog:  "click_tracker_log",
	ClickTrackerSet:  "click_tracker_set",
	Organization:     "organization",
	SchemaMigrations: "schema_migrations",
	User:             "user",
}
