// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mysqlmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// CapturePageSet is an object representing the database table.
type CapturePageSet struct {
	ID                     int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name                   string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	URLName                null.String `boil:"url_name" json:"url_name,omitempty" toml:"url_name" yaml:"url_name,omitempty"`
	SwitchDuration         int         `boil:"switch_duration" json:"switch_duration" toml:"switch_duration" yaml:"switch_duration"`
	OrganizationRefID      null.Int    `boil:"organization_ref_id" json:"organization_ref_id,omitempty" toml:"organization_ref_id" yaml:"organization_ref_id,omitempty"`
	AnalyticsNumberOfForms int         `boil:"analytics_number_of_forms" json:"analytics_number_of_forms" toml:"analytics_number_of_forms" yaml:"analytics_number_of_forms"`
	AnalyticsImpressions   int         `boil:"analytics_impressions" json:"analytics_impressions" toml:"analytics_impressions" yaml:"analytics_impressions"`
	AnalyticsSubmissions   int         `boil:"analytics_submissions" json:"analytics_submissions" toml:"analytics_submissions" yaml:"analytics_submissions"`
	AnalyticsLastUpdatedAt int         `boil:"analytics_last_updated_at" json:"analytics_last_updated_at" toml:"analytics_last_updated_at" yaml:"analytics_last_updated_at"`
	CreatedBy              null.Int    `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	LastUpdatedBy          null.Int    `boil:"last_updated_by" json:"last_updated_by,omitempty" toml:"last_updated_by" yaml:"last_updated_by,omitempty"`
	CreatedAt              time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	LastUpdatedAt          null.Time   `boil:"last_updated_at" json:"last_updated_at,omitempty" toml:"last_updated_at" yaml:"last_updated_at,omitempty"`
	IsActive               bool        `boil:"is_active" json:"is_active" toml:"is_active" yaml:"is_active"`

	R *capturePageSetR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L capturePageSetL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CapturePageSetColumns = struct {
	ID                     string
	Name                   string
	URLName                string
	SwitchDuration         string
	OrganizationRefID      string
	AnalyticsNumberOfForms string
	AnalyticsImpressions   string
	AnalyticsSubmissions   string
	AnalyticsLastUpdatedAt string
	CreatedBy              string
	LastUpdatedBy          string
	CreatedAt              string
	LastUpdatedAt          string
	IsActive               string
}{
	ID:                     "id",
	Name:                   "name",
	URLName:                "url_name",
	SwitchDuration:         "switch_duration",
	OrganizationRefID:      "organization_ref_id",
	AnalyticsNumberOfForms: "analytics_number_of_forms",
	AnalyticsImpressions:   "analytics_impressions",
	AnalyticsSubmissions:   "analytics_submissions",
	AnalyticsLastUpdatedAt: "analytics_last_updated_at",
	CreatedBy:              "created_by",
	LastUpdatedBy:          "last_updated_by",
	CreatedAt:              "created_at",
	LastUpdatedAt:          "last_updated_at",
	IsActive:               "is_active",
}

var CapturePageSetTableColumns = struct {
	ID                     string
	Name                   string
	URLName                string
	SwitchDuration         string
	OrganizationRefID      string
	AnalyticsNumberOfForms string
	AnalyticsImpressions   string
	AnalyticsSubmissions   string
	AnalyticsLastUpdatedAt string
	CreatedBy              string
	LastUpdatedBy          string
	CreatedAt              string
	LastUpdatedAt          string
	IsActive               string
}{
	ID:                     "capture_page_set.id",
	Name:                   "capture_page_set.name",
	URLName:                "capture_page_set.url_name",
	SwitchDuration:         "capture_page_set.switch_duration",
	OrganizationRefID:      "capture_page_set.organization_ref_id",
	AnalyticsNumberOfForms: "capture_page_set.analytics_number_of_forms",
	AnalyticsImpressions:   "capture_page_set.analytics_impressions",
	AnalyticsSubmissions:   "capture_page_set.analytics_submissions",
	AnalyticsLastUpdatedAt: "capture_page_set.analytics_last_updated_at",
	CreatedBy:              "capture_page_set.created_by",
	LastUpdatedBy:          "capture_page_set.last_updated_by",
	CreatedAt:              "capture_page_set.created_at",
	LastUpdatedAt:          "capture_page_set.last_updated_at",
	IsActive:               "capture_page_set.is_active",
}

// Generated where

var CapturePageSetWhere = struct {
	ID                     whereHelperint
	Name                   whereHelperstring
	URLName                whereHelpernull_String
	SwitchDuration         whereHelperint
	OrganizationRefID      whereHelpernull_Int
	AnalyticsNumberOfForms whereHelperint
	AnalyticsImpressions   whereHelperint
	AnalyticsSubmissions   whereHelperint
	AnalyticsLastUpdatedAt whereHelperint
	CreatedBy              whereHelpernull_Int
	LastUpdatedBy          whereHelpernull_Int
	CreatedAt              whereHelpertime_Time
	LastUpdatedAt          whereHelpernull_Time
	IsActive               whereHelperbool
}{
	ID:                     whereHelperint{field: "`capture_page_set`.`id`"},
	Name:                   whereHelperstring{field: "`capture_page_set`.`name`"},
	URLName:                whereHelpernull_String{field: "`capture_page_set`.`url_name`"},
	SwitchDuration:         whereHelperint{field: "`capture_page_set`.`switch_duration`"},
	OrganizationRefID:      whereHelpernull_Int{field: "`capture_page_set`.`organization_ref_id`"},
	AnalyticsNumberOfForms: whereHelperint{field: "`capture_page_set`.`analytics_number_of_forms`"},
	AnalyticsImpressions:   whereHelperint{field: "`capture_page_set`.`analytics_impressions`"},
	AnalyticsSubmissions:   whereHelperint{field: "`capture_page_set`.`analytics_submissions`"},
	AnalyticsLastUpdatedAt: whereHelperint{field: "`capture_page_set`.`analytics_last_updated_at`"},
	CreatedBy:              whereHelpernull_Int{field: "`capture_page_set`.`created_by`"},
	LastUpdatedBy:          whereHelpernull_Int{field: "`capture_page_set`.`last_updated_by`"},
	CreatedAt:              whereHelpertime_Time{field: "`capture_page_set`.`created_at`"},
	LastUpdatedAt:          whereHelpernull_Time{field: "`capture_page_set`.`last_updated_at`"},
	IsActive:               whereHelperbool{field: "`capture_page_set`.`is_active`"},
}

// CapturePageSetRels is where relationship names are stored.
var CapturePageSetRels = struct {
	CreatedByUser     string
	LastUpdatedByUser string
	OrganizationRef   string
	CapturePages      string
}{
	CreatedByUser:     "CreatedByUser",
	LastUpdatedByUser: "LastUpdatedByUser",
	OrganizationRef:   "OrganizationRef",
	CapturePages:      "CapturePages",
}

// capturePageSetR is where relationships are stored.
type capturePageSetR struct {
	CreatedByUser     *User            `boil:"CreatedByUser" json:"CreatedByUser" toml:"CreatedByUser" yaml:"CreatedByUser"`
	LastUpdatedByUser *User            `boil:"LastUpdatedByUser" json:"LastUpdatedByUser" toml:"LastUpdatedByUser" yaml:"LastUpdatedByUser"`
	OrganizationRef   *Organization    `boil:"OrganizationRef" json:"OrganizationRef" toml:"OrganizationRef" yaml:"OrganizationRef"`
	CapturePages      CapturePageSlice `boil:"CapturePages" json:"CapturePages" toml:"CapturePages" yaml:"CapturePages"`
}

// NewStruct creates a new relationship struct
func (*capturePageSetR) NewStruct() *capturePageSetR {
	return &capturePageSetR{}
}

func (r *capturePageSetR) GetCreatedByUser() *User {
	if r == nil {
		return nil
	}
	return r.CreatedByUser
}

func (r *capturePageSetR) GetLastUpdatedByUser() *User {
	if r == nil {
		return nil
	}
	return r.LastUpdatedByUser
}

func (r *capturePageSetR) GetOrganizationRef() *Organization {
	if r == nil {
		return nil
	}
	return r.OrganizationRef
}

func (r *capturePageSetR) GetCapturePages() CapturePageSlice {
	if r == nil {
		return nil
	}
	return r.CapturePages
}

// capturePageSetL is where Load methods for each relationship are stored.
type capturePageSetL struct{}

var (
	capturePageSetAllColumns            = []string{"id", "name", "url_name", "switch_duration", "organization_ref_id", "analytics_number_of_forms", "analytics_impressions", "analytics_submissions", "analytics_last_updated_at", "created_by", "last_updated_by", "created_at", "last_updated_at", "is_active"}
	capturePageSetColumnsWithoutDefault = []string{"name", "url_name", "switch_duration", "organization_ref_id", "created_by", "last_updated_by", "last_updated_at"}
	capturePageSetColumnsWithDefault    = []string{"id", "analytics_number_of_forms", "analytics_impressions", "analytics_submissions", "analytics_last_updated_at", "created_at", "is_active"}
	capturePageSetPrimaryKeyColumns     = []string{"id"}
	capturePageSetGeneratedColumns      = []string{}
)

type (
	// CapturePageSetSlice is an alias for a slice of pointers to CapturePageSet.
	// This should almost always be used instead of []CapturePageSet.
	CapturePageSetSlice []*CapturePageSet

	capturePageSetQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	capturePageSetType                 = reflect.TypeOf(&CapturePageSet{})
	capturePageSetMapping              = queries.MakeStructMapping(capturePageSetType)
	capturePageSetPrimaryKeyMapping, _ = queries.BindMapping(capturePageSetType, capturePageSetMapping, capturePageSetPrimaryKeyColumns)
	capturePageSetInsertCacheMut       sync.RWMutex
	capturePageSetInsertCache          = make(map[string]insertCache)
	capturePageSetUpdateCacheMut       sync.RWMutex
	capturePageSetUpdateCache          = make(map[string]updateCache)
	capturePageSetUpsertCacheMut       sync.RWMutex
	capturePageSetUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single capturePageSet record from the query.
func (q capturePageSetQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CapturePageSet, error) {
	o := &CapturePageSet{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "mysqlmodel: failed to execute a one query for capture_page_set")
	}

	return o, nil
}

// All returns all CapturePageSet records from the query.
func (q capturePageSetQuery) All(ctx context.Context, exec boil.ContextExecutor) (CapturePageSetSlice, error) {
	var o []*CapturePageSet

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "mysqlmodel: failed to assign all query results to CapturePageSet slice")
	}

	return o, nil
}

// Count returns the count of all CapturePageSet records in the query.
func (q capturePageSetQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: failed to count capture_page_set rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q capturePageSetQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "mysqlmodel: failed to check if capture_page_set exists")
	}

	return count > 0, nil
}

// CreatedByUser pointed to by the foreign key.
func (o *CapturePageSet) CreatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.CreatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LastUpdatedByUser pointed to by the foreign key.
func (o *CapturePageSet) LastUpdatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.LastUpdatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// OrganizationRef pointed to by the foreign key.
func (o *CapturePageSet) OrganizationRef(mods ...qm.QueryMod) organizationQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.OrganizationRefID),
	}

	queryMods = append(queryMods, mods...)

	return Organizations(queryMods...)
}

// CapturePages retrieves all the capture_page's CapturePages with an executor.
func (o *CapturePageSet) CapturePages(mods ...qm.QueryMod) capturePageQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`capture_page`.`capture_page_set_id`=?", o.ID),
	)

	return CapturePages(queryMods...)
}

// LoadCreatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (capturePageSetL) LoadCreatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCapturePageSet interface{}, mods queries.Applicator) error {
	var slice []*CapturePageSet
	var object *CapturePageSet

	if singular {
		var ok bool
		object, ok = maybeCapturePageSet.(*CapturePageSet)
		if !ok {
			object = new(CapturePageSet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCapturePageSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCapturePageSet))
			}
		}
	} else {
		s, ok := maybeCapturePageSet.(*[]*CapturePageSet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCapturePageSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCapturePageSet))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &capturePageSetR{}
		}
		if !queries.IsNil(object.CreatedBy) {
			args[object.CreatedBy] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &capturePageSetR{}
			}

			if !queries.IsNil(obj.CreatedBy) {
				args[obj.CreatedBy] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByCapturePageSets = append(foreign.R.CreatedByCapturePageSets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CreatedBy, foreign.ID) {
				local.R.CreatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByCapturePageSets = append(foreign.R.CreatedByCapturePageSets, local)
				break
			}
		}
	}

	return nil
}

// LoadLastUpdatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (capturePageSetL) LoadLastUpdatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCapturePageSet interface{}, mods queries.Applicator) error {
	var slice []*CapturePageSet
	var object *CapturePageSet

	if singular {
		var ok bool
		object, ok = maybeCapturePageSet.(*CapturePageSet)
		if !ok {
			object = new(CapturePageSet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCapturePageSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCapturePageSet))
			}
		}
	} else {
		s, ok := maybeCapturePageSet.(*[]*CapturePageSet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCapturePageSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCapturePageSet))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &capturePageSetR{}
		}
		if !queries.IsNil(object.LastUpdatedBy) {
			args[object.LastUpdatedBy] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &capturePageSetR{}
			}

			if !queries.IsNil(obj.LastUpdatedBy) {
				args[obj.LastUpdatedBy] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.LastUpdatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.LastUpdatedByCapturePageSets = append(foreign.R.LastUpdatedByCapturePageSets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.LastUpdatedBy, foreign.ID) {
				local.R.LastUpdatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.LastUpdatedByCapturePageSets = append(foreign.R.LastUpdatedByCapturePageSets, local)
				break
			}
		}
	}

	return nil
}

// LoadOrganizationRef allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (capturePageSetL) LoadOrganizationRef(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCapturePageSet interface{}, mods queries.Applicator) error {
	var slice []*CapturePageSet
	var object *CapturePageSet

	if singular {
		var ok bool
		object, ok = maybeCapturePageSet.(*CapturePageSet)
		if !ok {
			object = new(CapturePageSet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCapturePageSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCapturePageSet))
			}
		}
	} else {
		s, ok := maybeCapturePageSet.(*[]*CapturePageSet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCapturePageSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCapturePageSet))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &capturePageSetR{}
		}
		if !queries.IsNil(object.OrganizationRefID) {
			args[object.OrganizationRefID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &capturePageSetR{}
			}

			if !queries.IsNil(obj.OrganizationRefID) {
				args[obj.OrganizationRefID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`organization`),
		qm.WhereIn(`organization.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Organization")
	}

	var resultSlice []*Organization
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Organization")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for organization")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for organization")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.OrganizationRef = foreign
		if foreign.R == nil {
			foreign.R = &organizationR{}
		}
		foreign.R.OrganizationRefCapturePageSets = append(foreign.R.OrganizationRefCapturePageSets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.OrganizationRefID, foreign.ID) {
				local.R.OrganizationRef = foreign
				if foreign.R == nil {
					foreign.R = &organizationR{}
				}
				foreign.R.OrganizationRefCapturePageSets = append(foreign.R.OrganizationRefCapturePageSets, local)
				break
			}
		}
	}

	return nil
}

// LoadCapturePages allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (capturePageSetL) LoadCapturePages(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCapturePageSet interface{}, mods queries.Applicator) error {
	var slice []*CapturePageSet
	var object *CapturePageSet

	if singular {
		var ok bool
		object, ok = maybeCapturePageSet.(*CapturePageSet)
		if !ok {
			object = new(CapturePageSet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCapturePageSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCapturePageSet))
			}
		}
	} else {
		s, ok := maybeCapturePageSet.(*[]*CapturePageSet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCapturePageSet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCapturePageSet))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &capturePageSetR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &capturePageSetR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`capture_page`),
		qm.WhereIn(`capture_page.capture_page_set_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load capture_page")
	}

	var resultSlice []*CapturePage
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice capture_page")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on capture_page")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for capture_page")
	}

	if singular {
		object.R.CapturePages = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &capturePageR{}
			}
			foreign.R.CapturePageSet = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.CapturePageSetID {
				local.R.CapturePages = append(local.R.CapturePages, foreign)
				if foreign.R == nil {
					foreign.R = &capturePageR{}
				}
				foreign.R.CapturePageSet = local
				break
			}
		}
	}

	return nil
}

// SetCreatedByUser of the capturePageSet to the related item.
// Sets o.R.CreatedByUser to related.
// Adds o to related.R.CreatedByCapturePageSets.
func (o *CapturePageSet) SetCreatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `capture_page_set` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"created_by"}),
		strmangle.WhereClause("`", "`", 0, capturePageSetPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CreatedBy, related.ID)
	if o.R == nil {
		o.R = &capturePageSetR{
			CreatedByUser: related,
		}
	} else {
		o.R.CreatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByCapturePageSets: CapturePageSetSlice{o},
		}
	} else {
		related.R.CreatedByCapturePageSets = append(related.R.CreatedByCapturePageSets, o)
	}

	return nil
}

// RemoveCreatedByUser relationship.
// Sets o.R.CreatedByUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *CapturePageSet) RemoveCreatedByUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.CreatedBy, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("created_by")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.CreatedByUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.CreatedByCapturePageSets {
		if queries.Equal(o.CreatedBy, ri.CreatedBy) {
			continue
		}

		ln := len(related.R.CreatedByCapturePageSets)
		if ln > 1 && i < ln-1 {
			related.R.CreatedByCapturePageSets[i] = related.R.CreatedByCapturePageSets[ln-1]
		}
		related.R.CreatedByCapturePageSets = related.R.CreatedByCapturePageSets[:ln-1]
		break
	}
	return nil
}

// SetLastUpdatedByUser of the capturePageSet to the related item.
// Sets o.R.LastUpdatedByUser to related.
// Adds o to related.R.LastUpdatedByCapturePageSets.
func (o *CapturePageSet) SetLastUpdatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `capture_page_set` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"last_updated_by"}),
		strmangle.WhereClause("`", "`", 0, capturePageSetPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.LastUpdatedBy, related.ID)
	if o.R == nil {
		o.R = &capturePageSetR{
			LastUpdatedByUser: related,
		}
	} else {
		o.R.LastUpdatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			LastUpdatedByCapturePageSets: CapturePageSetSlice{o},
		}
	} else {
		related.R.LastUpdatedByCapturePageSets = append(related.R.LastUpdatedByCapturePageSets, o)
	}

	return nil
}

// RemoveLastUpdatedByUser relationship.
// Sets o.R.LastUpdatedByUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *CapturePageSet) RemoveLastUpdatedByUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.LastUpdatedBy, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("last_updated_by")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.LastUpdatedByUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.LastUpdatedByCapturePageSets {
		if queries.Equal(o.LastUpdatedBy, ri.LastUpdatedBy) {
			continue
		}

		ln := len(related.R.LastUpdatedByCapturePageSets)
		if ln > 1 && i < ln-1 {
			related.R.LastUpdatedByCapturePageSets[i] = related.R.LastUpdatedByCapturePageSets[ln-1]
		}
		related.R.LastUpdatedByCapturePageSets = related.R.LastUpdatedByCapturePageSets[:ln-1]
		break
	}
	return nil
}

// SetOrganizationRef of the capturePageSet to the related item.
// Sets o.R.OrganizationRef to related.
// Adds o to related.R.OrganizationRefCapturePageSets.
func (o *CapturePageSet) SetOrganizationRef(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Organization) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `capture_page_set` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"organization_ref_id"}),
		strmangle.WhereClause("`", "`", 0, capturePageSetPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.OrganizationRefID, related.ID)
	if o.R == nil {
		o.R = &capturePageSetR{
			OrganizationRef: related,
		}
	} else {
		o.R.OrganizationRef = related
	}

	if related.R == nil {
		related.R = &organizationR{
			OrganizationRefCapturePageSets: CapturePageSetSlice{o},
		}
	} else {
		related.R.OrganizationRefCapturePageSets = append(related.R.OrganizationRefCapturePageSets, o)
	}

	return nil
}

// RemoveOrganizationRef relationship.
// Sets o.R.OrganizationRef to nil.
// Removes o from all passed in related items' relationships struct.
func (o *CapturePageSet) RemoveOrganizationRef(ctx context.Context, exec boil.ContextExecutor, related *Organization) error {
	var err error

	queries.SetScanner(&o.OrganizationRefID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("organization_ref_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.OrganizationRef = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.OrganizationRefCapturePageSets {
		if queries.Equal(o.OrganizationRefID, ri.OrganizationRefID) {
			continue
		}

		ln := len(related.R.OrganizationRefCapturePageSets)
		if ln > 1 && i < ln-1 {
			related.R.OrganizationRefCapturePageSets[i] = related.R.OrganizationRefCapturePageSets[ln-1]
		}
		related.R.OrganizationRefCapturePageSets = related.R.OrganizationRefCapturePageSets[:ln-1]
		break
	}
	return nil
}

// AddCapturePages adds the given related objects to the existing relationships
// of the capture_page_set, optionally inserting them as new records.
// Appends related to o.R.CapturePages.
// Sets related.R.CapturePageSet appropriately.
func (o *CapturePageSet) AddCapturePages(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CapturePage) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.CapturePageSetID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `capture_page` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"capture_page_set_id"}),
				strmangle.WhereClause("`", "`", 0, capturePagePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.CapturePageSetID = o.ID
		}
	}

	if o.R == nil {
		o.R = &capturePageSetR{
			CapturePages: related,
		}
	} else {
		o.R.CapturePages = append(o.R.CapturePages, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &capturePageR{
				CapturePageSet: o,
			}
		} else {
			rel.R.CapturePageSet = o
		}
	}
	return nil
}

// CapturePageSets retrieves all the records using an executor.
func CapturePageSets(mods ...qm.QueryMod) capturePageSetQuery {
	mods = append(mods, qm.From("`capture_page_set`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`capture_page_set`.*"})
	}

	return capturePageSetQuery{q}
}

// FindCapturePageSet retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCapturePageSet(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*CapturePageSet, error) {
	capturePageSetObj := &CapturePageSet{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `capture_page_set` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, capturePageSetObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "mysqlmodel: unable to select from capture_page_set")
	}

	return capturePageSetObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CapturePageSet) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("mysqlmodel: no capture_page_set provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(capturePageSetColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	capturePageSetInsertCacheMut.RLock()
	cache, cached := capturePageSetInsertCache[key]
	capturePageSetInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			capturePageSetAllColumns,
			capturePageSetColumnsWithDefault,
			capturePageSetColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(capturePageSetType, capturePageSetMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(capturePageSetType, capturePageSetMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `capture_page_set` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `capture_page_set` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `capture_page_set` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, capturePageSetPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "mysqlmodel: unable to insert into capture_page_set")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == capturePageSetMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "mysqlmodel: unable to populate default values for capture_page_set")
	}

CacheNoHooks:
	if !cached {
		capturePageSetInsertCacheMut.Lock()
		capturePageSetInsertCache[key] = cache
		capturePageSetInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the CapturePageSet.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CapturePageSet) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	capturePageSetUpdateCacheMut.RLock()
	cache, cached := capturePageSetUpdateCache[key]
	capturePageSetUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			capturePageSetAllColumns,
			capturePageSetPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("mysqlmodel: unable to update capture_page_set, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `capture_page_set` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, capturePageSetPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(capturePageSetType, capturePageSetMapping, append(wl, capturePageSetPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: unable to update capture_page_set row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: failed to get rows affected by update for capture_page_set")
	}

	if !cached {
		capturePageSetUpdateCacheMut.Lock()
		capturePageSetUpdateCache[key] = cache
		capturePageSetUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q capturePageSetQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: unable to update all for capture_page_set")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: unable to retrieve rows affected for capture_page_set")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CapturePageSetSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("mysqlmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), capturePageSetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `capture_page_set` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, capturePageSetPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: unable to update all in capturePageSet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: unable to retrieve rows affected all in update all capturePageSet")
	}
	return rowsAff, nil
}

var mySQLCapturePageSetUniqueColumns = []string{
	"id",
	"name",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CapturePageSet) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("mysqlmodel: no capture_page_set provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(capturePageSetColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLCapturePageSetUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	capturePageSetUpsertCacheMut.RLock()
	cache, cached := capturePageSetUpsertCache[key]
	capturePageSetUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			capturePageSetAllColumns,
			capturePageSetColumnsWithDefault,
			capturePageSetColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			capturePageSetAllColumns,
			capturePageSetPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("mysqlmodel: unable to upsert capture_page_set, could not build update column list")
		}

		ret := strmangle.SetComplement(capturePageSetAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`capture_page_set`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `capture_page_set` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(capturePageSetType, capturePageSetMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(capturePageSetType, capturePageSetMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "mysqlmodel: unable to upsert for capture_page_set")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == capturePageSetMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(capturePageSetType, capturePageSetMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "mysqlmodel: unable to retrieve unique values for capture_page_set")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "mysqlmodel: unable to populate default values for capture_page_set")
	}

CacheNoHooks:
	if !cached {
		capturePageSetUpsertCacheMut.Lock()
		capturePageSetUpsertCache[key] = cache
		capturePageSetUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single CapturePageSet record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CapturePageSet) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("mysqlmodel: no CapturePageSet provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), capturePageSetPrimaryKeyMapping)
	sql := "DELETE FROM `capture_page_set` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: unable to delete from capture_page_set")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: failed to get rows affected by delete for capture_page_set")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q capturePageSetQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("mysqlmodel: no capturePageSetQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: unable to delete all from capture_page_set")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: failed to get rows affected by deleteall for capture_page_set")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CapturePageSetSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), capturePageSetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `capture_page_set` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, capturePageSetPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: unable to delete all from capturePageSet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysqlmodel: failed to get rows affected by deleteall for capture_page_set")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CapturePageSet) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCapturePageSet(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CapturePageSetSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CapturePageSetSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), capturePageSetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `capture_page_set`.* FROM `capture_page_set` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, capturePageSetPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "mysqlmodel: unable to reload all in CapturePageSetSlice")
	}

	*o = slice

	return nil
}

// CapturePageSetExists checks if the CapturePageSet row exists.
func CapturePageSetExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `capture_page_set` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "mysqlmodel: unable to check if capture_page_set exists")
	}

	return exists, nil
}

// Exists checks if the CapturePageSet row exists.
func (o *CapturePageSet) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CapturePageSetExists(ctx, exec, o.ID)
}
